'use client'

import { useCallback, useEffect, useState } from 'react'
import { Check, MessageCircle, Save, ShieldCheck, Users } from 'lucide-react'
import { api } from '@/lib/client-api'
import { Badge, Button, Card, ErrorNote, Field, Spinner, inputCls } from '@/components/ui'

type Settings = { enabled: boolean; swapEnabled: boolean; saleEnabled: boolean; openSaleEnabled: boolean; dailyRosterEnabled: boolean; personalReminderEnabled: boolean; showPhoneInDailyRoster: boolean; dailyRosterHour: number; personalReminderHour: number }
type LineData = {
  settings: Settings
  accounts: { id: string; user_id: string; line_user_id: string; status: string; linked_at: string; last_seen_at: string | null; profile: { name: string; role: string; dept: string | null } | null }[]
  groups: { id: string; line_group_id: string; name: string | null; group_type: string; is_approved: boolean; is_active: boolean; daily_roster_enabled: boolean; show_phone_in_daily_roster: boolean; created_at: string }[]
  logs: { id: string; recipient_type: string; message_type: string; status: string; attempts: number; error_code: string | null; created_at: string; sent_at: string | null }[]
  webhookEvents: { id: string; webhook_event_id: string; event_type: string | null; line_user_id: string | null; line_group_id: string | null; status: string; attempts: number; error_code: string | null; created_at: string; processed_at: string | null }[]
}

function mask(value: string) { return value.length > 10 ? `${value.slice(0, 6)}…${value.slice(-4)}` : value }

export function LineIntegrationView() {
  const [data, setData] = useState<LineData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { try { setError(null); setData(await api<LineData>('/api/admin/line')) } catch (reason) { setError(reason instanceof Error ? reason.message : 'โหลดไม่สำเร็จ') } }, [])
  useEffect(() => { void load() }, [load])
  async function save(patch: Partial<Settings>) { if (!data) return; setBusy(true); try { const result = await api<{ settings: Settings }>('/api/admin/line', { method: 'PUT', body: JSON.stringify(patch) }); setData({ ...data, settings: result.settings }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'บันทึกไม่สำเร็จ') } finally { setBusy(false) } }
  async function updateGroup(groupId: string, patch: Record<string, boolean>) { setBusy(true); try { await api('/api/admin/line', { method: 'PATCH', body: JSON.stringify({ groupId, ...patch }) }); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'แก้ไขกลุ่มไม่สำเร็จ') } finally { setBusy(false) } }
  async function updateAccount(accountId: string, action: 'disable' | 'enable' | 'unlink') {
    const labels = { disable: 'ปิดใช้งาน', enable: 'เปิดใช้งาน', unlink: 'ยกเลิกการเชื่อม' }
    if (!window.confirm(`ต้องการ${labels[action]}บัญชีนี้หรือไม่?`)) return
    setBusy(true)
    try { await api(`/api/admin/line/accounts/${accountId}`, { method: 'PATCH', body: JSON.stringify({ action }) }); await load() }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'แก้ไขบัญชี LINE ไม่สำเร็จ') }
    finally { setBusy(false) }
  }
  if (!data) return <div><ErrorNote error={error} /><Spinner /></div>
  const s = data.settings
  const switches: [keyof Settings, string][] = [['enabled', 'เปิดใช้งาน LINE integration'], ['swapEnabled', 'แลกเวรผ่าน MINI App'], ['saleEnabled', 'ขาย/รับเวรผ่าน MINI App'], ['openSaleEnabled', 'ประกาศขายแบบรับคนแรก (LINE เท่านั้น)'], ['dailyRosterEnabled', 'สรุปเวรประจำวันเข้ากลุ่ม'], ['personalReminderEnabled', 'เตือนเวรส่วนตัว'], ['showPhoneInDailyRoster', 'อนุญาตแสดงเบอร์ในสรุปเวร']]
  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-100 text-brand-700"><MessageCircle size={21} /></div><div><h1 className="text-lg font-bold">LINE Integration</h1><p className="text-sm text-slate-500">ควบคุม feature flag, การเชื่อมบัญชี และกลุ่มที่รับสรุปเวร</p></div></div>
      <ErrorNote error={error} />
      <Card className="flex flex-col gap-3"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">Feature flags</h2><p className="text-xs text-slate-500">ปิดทั้งหมดเป็นค่าเริ่มต้นจนกว่าจะตั้งค่า LINE Console ครบ</p></div><ShieldCheck size={18} className={s.enabled ? 'text-emerald-600' : 'text-slate-300'} /></div><div className="divide-y divide-slate-100">{switches.map(([key, label]) => <label key={key} className="flex min-h-12 items-center justify-between gap-3 text-sm"><span>{label}</span><input type="checkbox" checked={Boolean(s[key])} disabled={busy || (key !== 'enabled' && !s.enabled)} onChange={(event) => save({ [key]: event.target.checked })} className="h-5 w-5 accent-brand-600" /></label>)}</div><div className="grid gap-3 sm:grid-cols-2"><Field label="เวลาสรุปเวร (ICT)"><input type="number" min={0} max={23} className={inputCls} value={s.dailyRosterHour} onChange={(event) => setData({ ...data, settings: { ...s, dailyRosterHour: Number(event.target.value) } })} onBlur={() => save({ dailyRosterHour: s.dailyRosterHour })} /></Field><Field label="เวลาเตือนส่วนตัว (ICT)"><input type="number" min={0} max={23} className={inputCls} value={s.personalReminderHour} onChange={(event) => setData({ ...data, settings: { ...s, personalReminderHour: Number(event.target.value) } })} onBlur={() => save({ personalReminderHour: s.personalReminderHour })} /></Field></div><Button size="sm" variant="outline" disabled={busy} onClick={() => save(s)} className="self-start"><Save size={15} />บันทึกค่า LINE ทั้งหมด</Button></Card>
      <Card><div className="mb-3 flex items-center gap-2"><Users size={18} className="text-brand-700" /><h2 className="text-sm font-bold">บัญชีที่เชื่อมแล้ว ({data.accounts.length})</h2></div>{data.accounts.length ? <div className="space-y-2">{data.accounts.map((account) => <div key={account.id} className="rounded-xl border border-line px-3 py-2 text-sm"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{account.profile?.name || account.user_id}</p><p className="truncate text-[11px] text-slate-500">{mask(account.line_user_id)} · {account.profile?.role || '—'}</p></div><Badge tone={account.status === 'active' ? 'green' : account.status === 'blocked' ? 'red' : 'gray'}>{account.status}</Badge></div><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy || account.status === 'blocked'} onClick={() => updateAccount(account.id, account.status === 'active' ? 'disable' : 'enable')}>{account.status === 'active' ? 'ปิดใช้งาน' : 'เปิดใช้งาน'}</Button><Button size="sm" variant="danger" disabled={busy || account.status === 'blocked'} onClick={() => updateAccount(account.id, 'unlink')}>ยกเลิกการเชื่อม</Button></div></div>)}</div> : <p className="text-sm text-slate-500">ยังไม่มีบัญชีที่เชื่อม</p>}</Card>
      <Card><div className="mb-3 flex items-center gap-2"><Users size={18} className="text-brand-700" /><h2 className="text-sm font-bold">กลุ่ม LINE ({data.groups.length})</h2></div>{data.groups.length ? <div className="space-y-2">{data.groups.map((group) => <div key={group.id} className="rounded-xl border border-line p-3"><div className="flex items-center justify-between gap-2"><div><p className="font-semibold">{group.name || mask(group.line_group_id)}</p><p className="text-[11px] text-slate-500">{group.group_type} · {group.is_active ? 'active' : 'รอเปิดใช้งาน'}</p></div><Badge tone={group.is_approved ? 'green' : 'amber'}>{group.is_approved ? 'อนุมัติแล้ว' : 'รออนุมัติ'}</Badge></div><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant={group.is_approved ? 'outline' : 'success'} disabled={busy} onClick={() => updateGroup(group.id, group.is_approved ? { isApproved: false } : { isApproved: true, isActive: true })}>{group.is_approved ? 'ยกเลิกอนุมัติ' : <><Check size={14} />อนุมัติ</>}</Button>{group.is_approved && <Button size="sm" variant="outline" disabled={busy} onClick={() => updateGroup(group.id, { dailyRosterEnabled: !group.daily_roster_enabled })}>{group.daily_roster_enabled ? 'ปิดสรุปเวร' : 'เปิดสรุปเวร'}</Button>}{group.is_approved && group.daily_roster_enabled && <Button size="sm" variant="outline" disabled={busy} onClick={() => updateGroup(group.id, { showPhoneInDailyRoster: !group.show_phone_in_daily_roster })}>{group.show_phone_in_daily_roster ? 'ซ่อนเบอร์' : 'แสดงเบอร์'}</Button>}<Button size="sm" variant="outline" disabled={busy || !group.is_approved} onClick={() => updateGroup(group.id, { isActive: !group.is_active })}>{group.is_active ? 'ปิดกลุ่ม' : 'เปิดกลุ่ม'}</Button></div></div>)}</div> : <p className="text-sm text-slate-500">ยังไม่มีกลุ่มส่ง join event</p>}</Card>
      <Card><h2 className="mb-3 text-sm font-bold">Message outbox ล่าสุด</h2>{data.logs.length ? <div className="space-y-2">{data.logs.slice(0, 30).map((log) => <div key={log.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-2 text-xs"><div><p className="font-semibold">{log.message_type}</p><p className="text-slate-400">{log.recipient_type} · {new Date(log.created_at).toLocaleString('th-TH')}</p></div><Badge tone={log.status === 'sent' ? 'green' : log.status === 'dead' ? 'red' : 'amber'}>{log.status}</Badge></div>)}</div> : <p className="text-sm text-slate-500">ยังไม่มีข้อความในคิว</p>}</Card>
      <Card><h2 className="mb-3 text-sm font-bold">Webhook logs ล่าสุด</h2>{data.webhookEvents.length ? <div className="space-y-2">{data.webhookEvents.slice(0, 30).map((event) => <div key={event.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-2 text-xs"><div><p className="font-semibold">{event.event_type || 'unknown'} · {mask(event.webhook_event_id)}</p><p className="text-slate-400">attempt {event.attempts} · {new Date(event.created_at).toLocaleString('th-TH')}</p></div><Badge tone={event.status === 'processed' ? 'green' : event.status === 'failed' ? 'red' : 'amber'}>{event.status}</Badge></div>)}</div> : <p className="text-sm text-slate-500">ยังไม่มี webhook</p>}</Card>
    </div>
  )
}
